### ISSUE TITLE
not redirect back to app from zarinpal IOS

### ISSUE THREAD

**Issue by mr-mamali** [irdeveloper89/zarinpal#1]
android works finde , but iOS:

[Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    Authority = 000000000000000000000000000000024558;
    Status = OK;
}

when trying to return back in my application , in console i received this message but app does not open , scheme and url are configured correctly in zarinpal package.

**Comment by irdeveloper89** [comment]
In url_launcher  set the forceSafariVC to false
